# Generated by Django 4.1 on 2022-11-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_alter_magazine_options_magazine_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='photo_magazine',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
