# Generated by Django 4.1 on 2022-12-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_alter_magazine_photo_magazine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='views',
            field=models.IntegerField(default=20),
        ),
    ]
